### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by DjamikTea** [MaxUNof/vk-slaves#3]
Привет, при попытки сделать что-то либо {'error': {'message': 'Server error'}}
![Снимок экрана 2021-03-26 в 07 03 00](https://user-images.githubusercontent.com/34600049/112575408-52c9cb00-8e01-11eb-80b4-9d2ca86f2080.png)

**Comment by altfoxie** [comment]
Привет. Игра лежит

**Comment by TheCaJlaT** [comment]
> 
> 
> Привет. Игра лежит

Есть способ это исправить, добавь в headers запорса
`"User-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"`
![изображение](https://user-images.githubusercontent.com/66368050/112639569-761c6680-8e51-11eb-92ab-da479ba32f0e.png)

**Comment by DjamikTea** [comment]
помогло спасибо!
